use Win32::Console;
my $CONSOLE = Win32::Console->new(STD_OUTPUT_HANDLE);
my $attr = $CONSOLE->Attr();
$CONSOLE->Attr($FG_YELLOW | $BG_GREEN);
print ("GitHub : https://github.com/Crybik \n");
use LWP::Simple;
print ("\n Enter the link : ");
my $url = <STDIN>;
chomp $url;
print ("Enter output path with the name \n : ");
my $file = <STDIN>;
chomp $file;
getstore($url, $file);
$CONSOLE->Attr($attr);
