use Win32::Console;
my $CONSOLE = Win32::Console->new(STD_OUTPUT_HANDLE);
my $attr = $CONSOLE->Attr();
$CONSOLE->Attr($FG_YELLOW | $BG_GREEN);
print ("\n WELCOME TO Glob2Raw \n ");
print ("GitHub : https://github.com/Crybik \n");
print ("Facebook : https://facebook.com/solx20 \n");
print ("Facebook2 : https://facebook.com/100027040380280 \n");
print ("---------------------------------------------------- \n ");
print ("This Script Coded by Crybik \n \n ");
print ("---------------------------------------------------- \n ");
use LWP::Simple;
print ("\n Enter the link : ");
my $url = <STDIN>;
chomp $url;
print ("Enter path of file : ");
my $file = <STDIN>;
chomp $file;
getstore($url, $file);
$CONSOLE->Attr($attr);